/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.UberCar;
import model.UberCarList;
import java.lang.Exception;

/**
 *
 * @author Milind
 */
public class CreateUberCarJPanel extends javax.swing.JPanel {
    private JPanel jPanelCreate;
    private UberCarList listCar;
    private UberCar car;

    /**
     * Creates new form CreateUberCarJPanel
     */
    public CreateUberCarJPanel(JPanel jPanelCreate , UberCarList listCar) {
        initComponents();
        this.jPanelCreate = jPanelCreate;
        this.listCar = listCar;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelBrandName = new javax.swing.JLabel();
        jLabelModelNumber = new javax.swing.JLabel();
        jLabelManufactureYear = new javax.swing.JLabel();
        jLabelMinSeats = new javax.swing.JLabel();
        jLabelMaxSeats = new javax.swing.JLabel();
        jLabelCarAvailability = new javax.swing.JLabel();
        jCheckBoxCarAvailabilty = new javax.swing.JCheckBox();
        jLabelCarSerialNumber = new javax.swing.JLabel();
        jLabelCarCity = new javax.swing.JLabel();
        jLabelMaintenanceCertificate = new javax.swing.JLabel();
        jCheckBoxMaintenanceCertificate = new javax.swing.JCheckBox();
        jButtonSave = new javax.swing.JButton();
        jTextFieldBrand = new javax.swing.JTextField();
        jTextFieldModelNum = new javax.swing.JTextField();
        jTextFieldYearOfManu = new javax.swing.JTextField();
        jTextFieldMinimumSeats = new javax.swing.JTextField();
        jTextFieldMaximumSeats = new javax.swing.JTextField();
        jTextFieldSerialNumber = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitle.setText("Register Car With Uber");

        jLabelBrandName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBrandName.setText("Brand Name:");

        jLabelModelNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModelNumber.setText("Model Number:");

        jLabelManufactureYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelManufactureYear.setText("Year of Manufacture:");

        jLabelMinSeats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMinSeats.setText("Minimum Seats:");

        jLabelMaxSeats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMaxSeats.setText("Maximum Seats:");

        jLabelCarAvailability.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarAvailability.setText("Is Car Available?");

        jCheckBoxCarAvailabilty.setText("Click for Yes");

        jLabelCarSerialNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarSerialNumber.setText("Serial Number:");

        jLabelCarCity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCarCity.setText("City:");

        jLabelMaintenanceCertificate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMaintenanceCertificate.setText("Maintenance Certificate:");

        jCheckBoxMaintenanceCertificate.setText("Click for Yes");

        jButtonSave.setText("REGISTER");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMaintenanceCertificate)
                            .addComponent(jLabelCarCity)
                            .addComponent(jLabelCarSerialNumber)
                            .addComponent(jLabelModelNumber)
                            .addComponent(jLabelBrandName)
                            .addComponent(jLabelManufactureYear)
                            .addComponent(jLabelMinSeats)
                            .addComponent(jLabelMaxSeats)
                            .addComponent(jLabelCarAvailability))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabelTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxMaintenanceCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxCarAvailabilty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldBrand)
                                    .addComponent(jTextFieldModelNum)
                                    .addComponent(jTextFieldYearOfManu)
                                    .addComponent(jTextFieldMinimumSeats)
                                    .addComponent(jTextFieldMaximumSeats)
                                    .addComponent(jTextFieldSerialNumber)
                                    .addComponent(jTextFieldCity)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButtonSave)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelTitle)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarSerialNumber)
                    .addComponent(jTextFieldSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBrandName)
                    .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelNumber)
                    .addComponent(jTextFieldModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManufactureYear)
                    .addComponent(jTextFieldYearOfManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinSeats)
                    .addComponent(jTextFieldMinimumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxSeats)
                    .addComponent(jTextFieldMaximumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCarAvailabilty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarAvailability))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarCity)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaintenanceCertificate)
                    .addComponent(jCheckBoxMaintenanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        int manufacturedYear=0;
        int minSeats=0;
        int maxSeats=0;
        if(jTextFieldBrand.equals("")){
        JOptionPane.showMessageDialog(null, "Brand name is mandatory");
            return;
        }
        String brand =jTextFieldBrand.getText(); 
        if(jTextFieldBrand.equals("")){
        JOptionPane.showMessageDialog(null, "Serial number is mandatory");
            return;
        }
        String serialNum=jTextFieldSerialNumber.getText();
        Boolean available = jCheckBoxCarAvailabilty.isSelected();
        try{
            if(!"".equals(jTextFieldYearOfManu.getText())){
           Integer.parseInt(jTextFieldYearOfManu.getText()); 
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numeric value for manufactured year");
            return;
        }
        if(!"".equals(jTextFieldYearOfManu.getText())){
         manufacturedYear = Integer.parseInt(jTextFieldYearOfManu.getText());
        }
        try{
            if(!"".equals(jTextFieldMinimumSeats.getText())){
           Integer.parseInt(jTextFieldMinimumSeats.getText()); 
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numeric value for minimum seats");
            return;
        }
        if(!"".equals(jTextFieldMinimumSeats.getText())){
        minSeats = Integer.parseInt(jTextFieldMinimumSeats.getText());
        }
        try{
            if(!"".equals(jTextFieldMaximumSeats.getText())){
           Integer.parseInt(jTextFieldMaximumSeats.getText()); 
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numeric value for maximum seats");
            return;
        }
        if(!"".equals(jTextFieldMaximumSeats.getText())){
         maxSeats = Integer.parseInt(jTextFieldMaximumSeats.getText());
        }
        
        try{
         
        
        for(UberCar car : listCar.getCarList()){
            Object[] row = new Object[10];
            /*row[0] = car;
            row[1] = car.getManufacturedYear();
            row[2] = car.getMinSeats();
            row[3] = car.getMaxSeats();
            row[4] = car.getAvailableCity();
            row[5] = car.getSerialNumber();
            row[6] = car.getModelNumber();
            row[7] = car.isMaintenanceCertificate();
            row[8] = car.isAvailable(); */
            
            
            if(car.getSerialNumber().equals(serialNum)){
                throw new Exception();
                  
            }
            else{
            serialNum = jTextFieldSerialNumber.getText();}
        }}
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "Serial Number already registered");
          return;
        }
        //String serialNum = jTextFieldSerialNumber.getText();
        String modelNum = jTextFieldModelNum.getText();
        String availableCity = jTextFieldCity.getText();
        Boolean maintenanceCertificate = jCheckBoxMaintenanceCertificate.isSelected();

         
        UberCar car = listCar.addCar(brand, manufacturedYear, minSeats, maxSeats, serialNum, modelNum, availableCity, maintenanceCertificate,available);
        car.setBrand(brand);
        car.setAvailable(available);
        car.setManufacturedYear(manufacturedYear);
        car.setMinSeats(minSeats);
        car.setMaxSeats(maxSeats);
        car.setSerialNumber(serialNum);
        car.setModelNumber(modelNum);
        car.setAvailableCity(availableCity);
        car.setMaintenanceCertificate(maintenanceCertificate);
        car.setAvailable(available);
        JOptionPane.showMessageDialog(null, "Car Registered successfully");
        listCar.setCurrentDate(new Date());
        jTextFieldBrand.setText("");
        jCheckBoxCarAvailabilty.setText("");
        jTextFieldYearOfManu.setText("");
        jTextFieldMinimumSeats.setText("");
        jTextFieldMaximumSeats.setText("");
        jTextFieldSerialNumber.setText("");
        jTextFieldModelNum.setText("");
        jTextFieldCity.setText("");
        jCheckBoxMaintenanceCertificate.setSelected(false);
        jCheckBoxCarAvailabilty.setSelected(false);
        
        /*Date date = new Date();  
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");  
        String strDate = dateFormat.format(date);
        listCar.setCurrentDate(date);*/
        
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxCarAvailabilty;
    private javax.swing.JCheckBox jCheckBoxMaintenanceCertificate;
    private javax.swing.JLabel jLabelBrandName;
    private javax.swing.JLabel jLabelCarAvailability;
    private javax.swing.JLabel jLabelCarCity;
    private javax.swing.JLabel jLabelCarSerialNumber;
    private javax.swing.JLabel jLabelMaintenanceCertificate;
    private javax.swing.JLabel jLabelManufactureYear;
    private javax.swing.JLabel jLabelMaxSeats;
    private javax.swing.JLabel jLabelMinSeats;
    private javax.swing.JLabel jLabelModelNumber;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldMaximumSeats;
    private javax.swing.JTextField jTextFieldMinimumSeats;
    private javax.swing.JTextField jTextFieldModelNum;
    private javax.swing.JTextField jTextFieldSerialNumber;
    private javax.swing.JTextField jTextFieldYearOfManu;
    // End of variables declaration//GEN-END:variables
}
