/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import model.Person;
import java.util.Date;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JTextField;
import java.time.LocalDate;
import java.util.Date;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.*;
import javax.swing.border.Border;



/**
 *
 * @author Milind
 */
public class CreateJPanel extends javax.swing.JPanel  {
    Person person;
   
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        lblTtile = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        lblPhNo = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedRecNo = new javax.swing.JLabel();
        lblHealthPlanNo = new javax.swing.JLabel();
        lblBkAccNo = new javax.swing.JLabel();
        lblLicNo = new javax.swing.JLabel();
        lblLicDoi = new javax.swing.JLabel();
        lblVehicleNo = new javax.swing.JLabel();
        lblLinkedInId = new javax.swing.JLabel();
        lblDevAdd = new javax.swing.JLabel();
        lblIpAdd = new javax.swing.JLabel();
        lblRetinalNo = new javax.swing.JLabel();
        lblFingerIdenNo = new javax.swing.JLabel();
        lblLocId = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedRecNo = new javax.swing.JTextField();
        txtHealthPlanNo = new javax.swing.JTextField();
        txtBkAccNo = new javax.swing.JTextField();
        txtLicNo = new javax.swing.JTextField();
        txtVehicleNo = new javax.swing.JTextField();
        txtDevAdd = new javax.swing.JTextField();
        txtLinkedInId = new javax.swing.JTextField();
        txtIpAdd = new javax.swing.JTextField();
        txtRetinalNo = new javax.swing.JTextField();
        txtFingerIdenNo = new javax.swing.JTextField();
        txtLocalIdNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        jDateChooserLDoi = new com.toedter.calendar.JDateChooser();
        lblFaxNo1 = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        btnAgeCalc = new javax.swing.JButton();
        lblSelectFile = new javax.swing.JLabel();
        txtSelectFile = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        lblErrZip = new javax.swing.JLabel();
        lblErrPhNo = new javax.swing.JLabel();
        lblErrFax = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrSsn = new javax.swing.JLabel();

        lblTtile.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        lblTtile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTtile.setText("Create");
        lblTtile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblFirstName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFirstName.setText("*First Name:");

        lblLastName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        lblStreet.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblStreet.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblState.setText("State:");

        lblZip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblZip.setText("*Zip:");

        lblPhNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPhNo.setText("*Phone Number:");

        lblDob.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDob.setText("*Date of birth:");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmail.setText("*Email:");

        lblSsn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSsn.setText("SSN:");

        lblMedRecNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMedRecNo.setText("Medical Record Number:");

        lblHealthPlanNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHealthPlanNo.setText("Health Plan Number:");

        lblBkAccNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBkAccNo.setText("Bank Account Number:");

        lblLicNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLicNo.setText("License Number:");

        lblLicDoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLicDoi.setText("License Date Of Issue:");

        lblVehicleNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVehicleNo.setText("Vehicle Number:");

        lblLinkedInId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLinkedInId.setText("LinkedIn Id:");

        lblDevAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDevAdd.setText("Device Address:");

        lblIpAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIpAdd.setText("IP Address:");

        lblRetinalNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRetinalNo.setText("Retinal Identification Number:");

        lblFingerIdenNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFingerIdenNo.setText("Fingerprint Identification Number:");

        lblLocId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLocId.setText("Local Id Number:");

        txtZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZipKeyReleased(evt);
            }
        });

        txtPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhNoKeyReleased(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtSsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSsnKeyReleased(evt);
            }
        });

        txtRetinalNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed(evt);
            }
        });

        txtFingerIdenNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed(evt);
            }
        });

        txtLocalIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavebtnSave2btnSaveActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAge.setText("Age:");

        txtAge.setEditable(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        jDateChooserDob.setMaxSelectableDate(new Date());
        jDateChooserDob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDobPropertyChange(evt);
            }
        });

        jDateChooserLDoi.setMaxSelectableDate(new Date());

        lblFaxNo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFaxNo1.setText("Fax Number:");

        txtFaxNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNoKeyReleased(evt);
            }
        });

        btnAgeCalc.setText("Calculate Age");
        btnAgeCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgeCalcActionPerformed(evt);
            }
        });

        lblSelectFile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSelectFile.setText("File Upload:");

        txtSelectFile.setEditable(false);
        txtSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        lblErrZip.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblErrZip.setForeground(new java.awt.Color(255, 0, 0));

        lblErrPhNo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblErrPhNo.setForeground(new java.awt.Color(255, 0, 51));

        lblErrFax.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblErrFax.setForeground(new java.awt.Color(255, 0, 0));

        lblErrEmail.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblErrEmail.setForeground(new java.awt.Color(255, 0, 0));

        lblErrSsn.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblErrSsn.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTtile, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSsn)
                                    .addComponent(lblMedRecNo)
                                    .addComponent(lblHealthPlanNo)
                                    .addComponent(lblBkAccNo)
                                    .addComponent(lblLicNo)
                                    .addComponent(lblLicDoi)
                                    .addComponent(lblVehicleNo)
                                    .addComponent(lblDevAdd)
                                    .addComponent(lblLinkedInId)
                                    .addComponent(lblIpAdd)
                                    .addComponent(lblRetinalNo)
                                    .addComponent(lblFingerIdenNo)
                                    .addComponent(lblLocId)
                                    .addComponent(lblSelectFile))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLocalIdNo)
                                                .addComponent(txtFingerIdenNo)
                                                .addComponent(txtRetinalNo)
                                                .addComponent(txtIpAdd)
                                                .addComponent(txtLinkedInId)
                                                .addComponent(txtDevAdd)
                                                .addComponent(txtVehicleNo)
                                                .addComponent(txtLicNo)
                                                .addComponent(txtBkAccNo)
                                                .addComponent(txtHealthPlanNo)
                                                .addComponent(txtMedRecNo)
                                                .addComponent(txtSsn)
                                                .addComponent(txtEmail)
                                                .addComponent(jDateChooserLDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnOpen)
                                            .addComponent(lblErrSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName)
                                    .addComponent(lblStreet)
                                    .addComponent(lblCity)
                                    .addComponent(lblState)
                                    .addComponent(lblZip)
                                    .addComponent(lblPhNo)
                                    .addComponent(lblDob)
                                    .addComponent(lblAge)
                                    .addComponent(lblFaxNo1))
                                .addGap(129, 129, 129)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserDob, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblErrEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                            .addComponent(lblErrZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAgeCalc)
                                            .addComponent(lblErrPhNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblErrFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lblTtile)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrPhNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgeCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jDateChooserDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrFax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrSsn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLicDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserLDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDevAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedInId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedInId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetinalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetinalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFingerIdenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFingerIdenNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(195, 195, 195))
        );

        jScrollPane1.setViewportView(jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed

    private void txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed

    private void txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void btnSavebtnSave2btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavebtnSave2btnSaveActionPerformed
        // TODO add your handling code here:
        String fn=txtFirstName.getText();
        //String dob=txtDob7.getText();
        String dateInsert  = ((JTextField)jDateChooserDob.getDateEditor().getUiComponent()).getText();
        String dateLicDoi  = ((JTextField)jDateChooserLDoi.getDateEditor().getUiComponent()).getText();
        System.out.println(dateInsert);
        String zipCode=txtZip.getText();
        String phNo=txtPhNo.getText();
        String faxNum=txtFaxNo.getText();
        String emailId=txtEmail.getText();
        String ssnNo=txtSsn.getText();
        
        
        
        /*boolean phFlag=false;
        if(phNo.length() !=10)
        {
            phFlag=true;
        }*/
        
        
        if(fn.equals("")){
            {
                JOptionPane.showMessageDialog(this,"Invalid First Name");
            }
        }
        /*else if(!checkForNumber(zipCode)){
            {
                JOptionPane.showMessageDialog(this,"Invalid Zip");
            }
        }*/
        /*else if((!checkForNumber(phNo)) | phFlag){
            
            
            {
                System.out.println("Inside Catch");
                JOptionPane.showMessageDialog(this,"Invalid Phone Number");
            }
        }*/
        /*else if(!dateValidate(dateInsert)){
        {
            
            JOptionPane.showMessageDialog(this,"Invalid date of birth");
            
        }
        }*/
        else if(!checkForNumber(faxNum)){
            {
                JOptionPane.showMessageDialog(this,"Invalid Fax Number");
            }
        }
        else if(!(emailId.contains("@"))){
            {
                JOptionPane.showMessageDialog(this,"Invalid Email Id");
            }
        }
        else if((ssnNo.length () != 9)){
            {
                JOptionPane.showMessageDialog(this,"Please enter valid 9 digit SSN number");
            }
        }
        else
        {
            person.setFirstName(fn);
            person.setLastName(txtLastName.getText());
            
            person.setStreet(txtStreet.getText());
            person.setCity(txtCity.getText());
            person.setState(txtState.getText());
            //person.setZip(Integer.parseInt(zipCode));
            person.setPhoneNo(phNo);
            person.setDob(dateInsert);
            person.setFaxNumber(faxNum);
            person.setEmail(emailId);
            person.setSsn(ssnNo);
            person.setMedRecNo(txtMedRecNo.getText());
            person.setHealthPlanNo(txtHealthPlanNo.getText());
            person.setBankAccount(txtBkAccNo.getText());
            person.setLicenseNo(txtLicNo.getText());
            person.setLicenseDOI(dateLicDoi);
            person.setVehicleNo(txtVehicleNo.getText());
            person.setDeviceAdd(txtDevAdd.getText());
            person.setLinkedInId(txtLinkedInId.getText());
            person.setIpAdd(txtIpAdd.getText());
            person.setRetinalIdenNo(txtRetinalNo.getText());
            person.setFingerIdenNo(txtFingerIdenNo.getText());
            person.setLocalIdNo(txtLocalIdNo.getText());
            
            
            
            
            
            
            
            
            
            
            
           
            
           
            
            
            

            JOptionPane.showMessageDialog(this,"Information saved");
        }
    }//GEN-LAST:event_btnSavebtnSave2btnSaveActionPerformed

    private void txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void btnAgeCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgeCalcActionPerformed
        // TODO add your handling code here:
        String dateInsert  = ((JTextField)jDateChooserDob.getDateEditor().getUiComponent()).getText();
        try {
            int ageInYears=findAge(dateInsert);
            System.out.println(ageInYears);
            person.setAge(ageInYears);
            txtAge.setText(Integer.toString(person.getAge()));
        } catch (ParseException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgeCalcActionPerformed

    private void txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        String getPath;
        JFileChooser chooseFile = new JFileChooser();
        chooseFile.showOpenDialog(null);
        File f = chooseFile.getSelectedFile();
        getPath = f.getAbsolutePath();
        String uploadPath = getPath;
//        System.out.println(restLogo);
        txtSelectFile.setText(uploadPath);
        person.setUploadPath(uploadPath);
       
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnOpenActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
         var emailId=txtEmail.getText();
        String PATTERN="^(.+)@(.+)$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(emailId);
        if (! match.matches()){
            lblErrEmail.setText("Enter Proper Format!!");
        }else{
        lblErrEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtSsnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSsnKeyReleased
        // TODO add your handling code here:
        String ssnNo=txtSsn.getText();
        String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ssnNo);
        if (! match.matches() | (ssnNo.length() !=9 )){
            lblErrSsn.setText("Enter Proper Format!!");
        }else{
        lblErrSsn.setText(null);
        }
        
    }//GEN-LAST:event_txtSsnKeyReleased

    private void txtPhNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhNoKeyReleased
        // TODO add your handling code here:
        String phNo=txtPhNo.getText();
        String PATTERN="^[0-9]{3}-[0-9]{3}-[0-9]{4}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(phNo);
        if (! match.matches()){
            lblErrPhNo.setText("Enter Proper Format!!");
        }else{
        lblErrPhNo.setText(null);
        }
        
        
         
    }//GEN-LAST:event_txtPhNoKeyReleased

    private void txtZipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipKeyReleased
        // TODO add your handling code here:
        String zipCode=txtZip.getText();
        String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(zipCode);
        if (! match.matches() | (zipCode.length() !=5 )){
            lblErrZip.setText("Enter Proper Format!!");
        }else{
        lblErrZip.setText(null);
        }
        
        
    }//GEN-LAST:event_txtZipKeyReleased

    private void txtFaxNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNoKeyReleased
        // TODO add your handling code here:
        String faxNo=txtFaxNo.getText();
        String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(faxNo);
        if (!match.matches()){
            lblErrFax.setText("Enter Proper Format!!");
        }else{
        lblErrFax.setText(null);
        }
        
    }//GEN-LAST:event_txtFaxNoKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jDateChooserDobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDobPropertyChange
        // TODO add your handling code here:
        String dateInsert  = ((JTextField)jDateChooserDob.getDateEditor().getUiComponent()).getText();
        try {
            int ageInYears=findAge(dateInsert);
            System.out.println(ageInYears);
            txtAge.setText("");
            person.setAge(ageInYears);
            txtAge.setText(Integer.toString(person.getAge()));
            
        } catch (ParseException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        
    }       
    }//GEN-LAST:event_jDateChooserDobPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgeCalc;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private com.toedter.calendar.JDateChooser jDateChooserLDoi;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBkAccNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDevAdd;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrFax;
    private javax.swing.JLabel lblErrPhNo;
    private javax.swing.JLabel lblErrSsn;
    private javax.swing.JLabel lblErrZip;
    private javax.swing.JLabel lblFaxNo1;
    private javax.swing.JLabel lblFingerIdenNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblIpAdd;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicDoi;
    private javax.swing.JLabel lblLicNo;
    private javax.swing.JLabel lblLinkedInId;
    private javax.swing.JLabel lblLocId;
    private javax.swing.JLabel lblMedRecNo;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblRetinalNo;
    private javax.swing.JLabel lblSelectFile;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTtile;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBkAccNo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDevAdd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFingerIdenNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtIpAdd;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicNo;
    private javax.swing.JTextField txtLinkedInId;
    private javax.swing.JTextField txtLocalIdNo;
    private javax.swing.JTextField txtMedRecNo;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtRetinalNo;
    private javax.swing.JTextField txtSelectFile;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtVehicleNo;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

    /*private static boolean dateValidate(String dob) {
        boolean dateFlag=true;
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        dateFormat.setLenient(false);
        try
        {
            Date formatted=dateFormat.parse(dob);
        }
        catch(Exception e)
                {
                    System.out.println(e);
                    dateFlag=false;
                  
                }
        return dateFlag;
    }*/
    
   /* private static boolean dateValidate(String dob)  {
        boolean dateFlag=true;
        try {
            
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            Date todayDate=new Date();
            String currentDate=dateFormat.format(todayDate);
            System.out.println(currentDate);
            Date dateDob = dateFormat.parse(dob);
            Date dateCurrent = dateFormat.parse(currentDate);
            int result=dateDob.compareTo(dateCurrent);
            System.out.println(result);
            if(result > 0)
            {
                dateFlag=false;
            }
            
            
        } catch (ParseException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
     
        }
        return dateFlag;
    }*/
    
    private static int findAge(String dob) throws ParseException  {
         int age=0;
        
           try{ 
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            Date birthDate=dateFormat.parse(dob);
            Instant instant = birthDate.toInstant();
            ZonedDateTime zone = instant.atZone(ZoneId.systemDefault());
            LocalDate givenDate = zone.toLocalDate();
            Period period = Period.between(givenDate, LocalDate.now());
            age=period.getYears();
            
            
            
        } catch (ParseException ex) {
            System.out.println("Problem with calculating age");
     
        }
        return age;
    }
    
  


    private static boolean checkForNumber(String numCheck) {
        boolean flag=true;
        try
        {
            Long.parseLong(numCheck);
                    
        }
        catch(Exception e)
                {
                   flag=false; 
        }
       return flag; 
    }
}
