/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.io.File;
import javax.swing.JOptionPane;
import model.Person;
import java.util.Date;
import javax.swing.JTextField;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.*;




/**
 *
 * @author Milind
 */
public class CreateJPanel extends javax.swing.JPanel  {
    Person person;
   
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        lblTtile = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        lblPhNo = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedRecNo = new javax.swing.JLabel();
        lblHealthPlanNo = new javax.swing.JLabel();
        lblBkAccNo = new javax.swing.JLabel();
        lblLicNo = new javax.swing.JLabel();
        lblLicDoi = new javax.swing.JLabel();
        lblVehicleNo = new javax.swing.JLabel();
        lblLinkedInId = new javax.swing.JLabel();
        lblDevAdd = new javax.swing.JLabel();
        lblIpAdd = new javax.swing.JLabel();
        lblRetinalNo = new javax.swing.JLabel();
        lblFingerIdenNo = new javax.swing.JLabel();
        lblLocId = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedRecNo = new javax.swing.JTextField();
        txtHealthPlanNo = new javax.swing.JTextField();
        txtBkAccNo = new javax.swing.JTextField();
        txtLicNo = new javax.swing.JTextField();
        txtVehicleNo = new javax.swing.JTextField();
        txtDevAdd = new javax.swing.JTextField();
        txtLinkedInId = new javax.swing.JTextField();
        txtIpAdd = new javax.swing.JTextField();
        txtRetinalNo = new javax.swing.JTextField();
        txtFingerIdenNo = new javax.swing.JTextField();
        txtLocalIdNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jDateChooserDob = new com.toedter.calendar.JDateChooser();
        jDateChooserLDoi = new com.toedter.calendar.JDateChooser();
        lblFaxNo1 = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        lblSelectFile = new javax.swing.JLabel();
        txtSelectFile = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        lblErrZip = new javax.swing.JLabel();
        lblErrPhNo = new javax.swing.JLabel();
        lblErrFax = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrSsn = new javax.swing.JLabel();
        lblErrFirstName = new javax.swing.JLabel();
        lblErrLast = new javax.swing.JLabel();
        lblErrCity = new javax.swing.JLabel();
        lblErrState = new javax.swing.JLabel();

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));

        lblTtile.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lblTtile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTtile.setText("Create");
        lblTtile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblFirstName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        lblStreet.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblStreet.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblState.setText("State:");

        lblZip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblZip.setText("Zip:");

        lblPhNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPhNo.setText("Phone Number:");

        lblDob.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDob.setText("Date of birth:");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmail.setText("Email:");

        lblSsn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSsn.setText("SSN:");

        lblMedRecNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMedRecNo.setText("Medical Record Number:");

        lblHealthPlanNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHealthPlanNo.setText("Health Plan Number:");

        lblBkAccNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBkAccNo.setText("Bank Account Number:");

        lblLicNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLicNo.setText("License Number:");

        lblLicDoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLicDoi.setText("License Date Of Issue:");

        lblVehicleNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVehicleNo.setText("Vehicle Number:");

        lblLinkedInId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLinkedInId.setText("LinkedIn Id:");

        lblDevAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDevAdd.setText("Device Address:");

        lblIpAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIpAdd.setText("IP Address:");

        lblRetinalNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRetinalNo.setText("Retinal Identification Number:");

        lblFingerIdenNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFingerIdenNo.setText("Fingerprint Identification Number:");

        lblLocId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLocId.setText("Local Id Number:");

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });

        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStateKeyReleased(evt);
            }
        });

        txtZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZipKeyReleased(evt);
            }
        });

        txtPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhNoKeyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtSsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSsnKeyReleased(evt);
            }
        });

        txtRetinalNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed(evt);
            }
        });

        txtFingerIdenNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed(evt);
            }
        });

        txtLocalIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavebtnSave2btnSaveActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAge.setText("Age(Years):");

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        jDateChooserDob.setMaxSelectableDate(new Date());
        jDateChooserDob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDobPropertyChange(evt);
            }
        });

        jDateChooserLDoi.setMaxSelectableDate(new Date());

        lblFaxNo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFaxNo1.setText("Fax Number:");

        txtFaxNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNoKeyReleased(evt);
            }
        });

        lblSelectFile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSelectFile.setText("File Upload:");

        txtSelectFile.setEditable(false);
        txtSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        lblErrZip.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrZip.setForeground(new java.awt.Color(255, 51, 51));

        lblErrPhNo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrPhNo.setForeground(new java.awt.Color(255, 51, 51));

        lblErrFax.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrFax.setForeground(new java.awt.Color(255, 51, 51));

        lblErrEmail.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrEmail.setForeground(new java.awt.Color(255, 51, 51));

        lblErrSsn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrSsn.setForeground(new java.awt.Color(255, 51, 51));

        lblErrFirstName.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrFirstName.setForeground(new java.awt.Color(255, 51, 51));

        lblErrLast.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrLast.setForeground(new java.awt.Color(255, 51, 51));

        lblErrCity.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrCity.setForeground(new java.awt.Color(255, 51, 51));

        lblErrState.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrState.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTtile, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSsn)
                                    .addComponent(lblMedRecNo)
                                    .addComponent(lblHealthPlanNo)
                                    .addComponent(lblBkAccNo)
                                    .addComponent(lblLicNo)
                                    .addComponent(lblLicDoi)
                                    .addComponent(lblVehicleNo)
                                    .addComponent(lblDevAdd)
                                    .addComponent(lblLinkedInId)
                                    .addComponent(lblIpAdd)
                                    .addComponent(lblRetinalNo)
                                    .addComponent(lblFingerIdenNo)
                                    .addComponent(lblLocId)
                                    .addComponent(lblSelectFile)
                                    .addComponent(lblFaxNo1))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLocalIdNo)
                                                .addComponent(txtFingerIdenNo)
                                                .addComponent(txtRetinalNo)
                                                .addComponent(txtIpAdd)
                                                .addComponent(txtLinkedInId)
                                                .addComponent(txtDevAdd)
                                                .addComponent(txtVehicleNo)
                                                .addComponent(txtLicNo)
                                                .addComponent(txtBkAccNo)
                                                .addComponent(txtHealthPlanNo)
                                                .addComponent(txtMedRecNo)
                                                .addComponent(txtSsn)
                                                .addComponent(txtEmail)
                                                .addComponent(jDateChooserLDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnOpen)
                                            .addComponent(lblErrSsn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName)
                                    .addComponent(lblStreet)
                                    .addComponent(lblCity)
                                    .addComponent(lblState)
                                    .addComponent(lblZip)
                                    .addComponent(lblPhNo)
                                    .addComponent(lblDob)
                                    .addComponent(lblAge))
                                .addGap(129, 129, 129)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserDob, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblErrEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                            .addComponent(lblErrZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblErrPhNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblErrFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTtile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrLast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrCity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrState, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrPhNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrFax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrSsn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserLDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLicDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDevAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedInId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedInId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetinalNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetinalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFingerIdenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFingerIdenNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(195, 195, 195))
        );

        jScrollPane1.setViewportView(jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetinalNotxtRetinalNo5txtRetinalNoActionPerformed

    private void txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFingerIdenNotxtFingerIdenNo10txtFingerIdenNoActionPerformed

    private void txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalIdNotxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void btnSavebtnSave2btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavebtnSave2btnSaveActionPerformed
        // TODO add your handling code here:
        
        String fn=person.getFirstName();
        String ln=person.getLastName();
        String city=person.getCity();
        String zipCode=Integer.toString(person.getZip());
        String phNo=person.getPhoneNo();
        String faxNum=person.getFaxNumber();
        String emailId=person.getEmail();
        String ssnNo=person.getSsn();
        String state=person.getState();
        String dateInsert  = ((JTextField)jDateChooserDob.getDateEditor().getUiComponent()).getText();
        String dateLicDoi  = ((JTextField)jDateChooserLDoi.getDateEditor().getUiComponent()).getText();
       
        
        
        
        if((lblErrFirstName.getText() != null)) {
            
            
            {
            JOptionPane.showMessageDialog(this,"Please enter valid first name");
           
            }
        }
        else if((lblErrLast.getText() != null)){
            {
                JOptionPane.showMessageDialog(this,"Please enter valid last name");
              
            }
        }
        else if((lblErrCity.getText() != null)){
            
            
            {
                JOptionPane.showMessageDialog(this,"Please enter valid city name");
                
            }
        }
        else if(lblErrState.getText() !=null && state!=null){
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid state name");
            
        }
        }
        else if(lblErrZip.getText() !=null && !zipCode.equals("0")){
            if(zipCode.length() !=5){
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid five digit zip code");
             }
        }}
        else if(lblErrPhNo.getText() != null && phNo!=null){
            
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid phone number");
             }
        }
        else if(lblErrFax.getText() != null && faxNum!=null){
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid fax number");
             }
        }
        else if(lblErrEmail.getText() != null && emailId!=null){
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid email id");
             }
        }
        else if(lblErrSsn.getText() != null && ssnNo!=null){
        {
            
            JOptionPane.showMessageDialog(this,"Please enter valid nine digit ssn number");
             }
        }
        
        else
        {
            
            person.setDob(dateInsert);
            person.setStreet(txtStreet.getText());
            person.setMedRecNo(txtMedRecNo.getText());
            person.setHealthPlanNo(txtHealthPlanNo.getText());
            person.setBankAccount(txtBkAccNo.getText());
            person.setLicenseNo(txtLicNo.getText());
            person.setLicenseDOI(dateLicDoi);
            person.setVehicleNo(txtVehicleNo.getText());
            person.setDeviceAdd(txtDevAdd.getText());
            person.setLinkedInId(txtLinkedInId.getText());
            person.setIpAdd(txtIpAdd.getText());
            person.setRetinalIdenNo(txtRetinalNo.getText());
            person.setFingerIdenNo(txtFingerIdenNo.getText());
            person.setLocalIdNo(txtLocalIdNo.getText());

            JOptionPane.showMessageDialog(this,"Information saved");
            txtFirstName.setText(null);
            txtLastName.setText(null);
            txtStreet.setText(null);
            txtCity.setText(null);
            txtState.setText(null);
            txtZip.setText(null);
            txtPhNo.setText(null);
            txtFaxNo.setText(null);
            txtEmail.setText(null);
            txtSsn.setText(null);
            txtMedRecNo.setText(null);
            txtHealthPlanNo.setText(null);
            txtBkAccNo.setText(null);
            txtLicNo.setText(null);
            jDateChooserLDoi.setCalendar(null);
            txtVehicleNo.setText(null);
            txtDevAdd.setText(null);
            txtLinkedInId.setText(null);
            txtIpAdd.setText(null);
            txtRetinalNo.setText(null);
            txtFingerIdenNo.setText(null);
            txtLocalIdNo.setText(null);
            txtSelectFile.setText(null);
            
            
            
            
            
            
        }
    }//GEN-LAST:event_btnSavebtnSave2btnSaveActionPerformed

    private void txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgetxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectFiletxtFingerIdenNo11txtFingerIdenNo1ActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        String getPath;
        JFileChooser chooseFile = new JFileChooser();
        FileNameExtensionFilter filterImage= new FileNameExtensionFilter("IMAGE_FILES","png","jpg","jpeg");
        chooseFile.addChoosableFileFilter(filterImage);
        int flag = chooseFile.showSaveDialog(null);
        if (flag == JFileChooser.APPROVE_OPTION){
        File selectedImageFile = chooseFile.getSelectedFile();
        String selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null, selectedImagePath);
        txtSelectFile.setText(selectedImagePath);
        person.setUploadPath(selectedImagePath);
            
        }     
    }//GEN-LAST:event_btnOpenActionPerformed

    private void jDateChooserDobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDobPropertyChange
        // TODO add your handling code here:
        
        String dateInsert  = ((JTextField)jDateChooserDob.getDateEditor().getUiComponent()).getText();
        try {
            
            int ageInYears=findAge(dateInsert);
            person.setAge(ageInYears);
            txtAge.setText(Integer.toString(person.getAge()));
        }catch (ParseException ex) {
            System.out.println("Error in calculating age");
        }    
    }//GEN-LAST:event_jDateChooserDobPropertyChange

    private void txtZipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipKeyReleased
        // TODO add your handling code here:
        String zipCode=txtZip.getText();
        String PATTERN="^[0-9]{5}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(zipCode);
        
        if (!match.matches()){    
        {
            
            lblErrZip.setText("Enter valid five digit zip!");
        }}else{
        lblErrZip.setText(null);
        person.setZip(Integer.parseInt(zipCode));
        }
    }//GEN-LAST:event_txtZipKeyReleased

    private void txtPhNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhNoKeyReleased
        // TODO add your handling code here:
        String phNo=txtPhNo.getText();
        String PATTERN="^[0-9]{3}-[0-9]{3}-[0-9]{4}$";
        //String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(phNo);
        if (!match.matches()){
            lblErrPhNo.setText("Enter valid phone number in format XXX-XXX-XXXX!!");
        }else{
        lblErrPhNo.setText(null);
        person.setPhoneNo(phNo);
        }
    }//GEN-LAST:event_txtPhNoKeyReleased

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        String fn=txtFirstName.getText();
        String PATTERN="^[a-zA-Z\\s]*$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(fn);
        if (!match.matches()){
            lblErrFirstName.setText("Invalid first name");
        }else{
        lblErrFirstName.setText(null);
        person.setFirstName(fn);
        }
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtSsnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSsnKeyReleased
        // TODO add your handling code here:
        String ssnNo=txtSsn.getText();
        String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ssnNo);
        if (! match.matches() | (ssnNo.length() !=9 )){
            lblErrSsn.setText("Enter nine digit SSN!!");
        }else{
        lblErrSsn.setText(null);
        person.setSsn(ssnNo);
        }
    }//GEN-LAST:event_txtSsnKeyReleased

    private void txtFaxNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNoKeyReleased
        // TODO add your handling code here:
        String faxNo=txtFaxNo.getText();
        String PATTERN="\\d+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(faxNo);
        if (!match.matches()){
            lblErrFax.setText("Invalid fax number. Only digits allowed!");
        }else{
        lblErrFax.setText(null);
        person.setFaxNumber(faxNo);
        }
    }//GEN-LAST:event_txtFaxNoKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        String city=txtCity.getText();
        String PATTERN="^[a-zA-Z\\s]*$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(city);
        if (!match.matches()){
            lblErrCity.setText("Invalid city");
        }else{
        lblErrCity.setText(null);
        person.setCity(city);
        }
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        var emailId=txtEmail.getText();
        String PATTERN="^(.+)@(.+)$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(emailId);
        if (! match.matches()){
            lblErrEmail.setText("Invalid email!");
        }else{
        lblErrEmail.setText(null);
        person.setEmail(emailId);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyReleased
        // TODO add your handling code here:
        String state=txtState.getText();
        String PATTERN="^[a-zA-Z\\s]*$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(state);
        if (!match.matches()){
            lblErrState.setText("Invalid state.");
        }else{
        lblErrState.setText(null);
        person.setState(state);
        }
    }//GEN-LAST:event_txtStateKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
        String ln=txtLastName.getText();
        String PATTERN="^[a-zA-Z\\s]*$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ln);
        if (!match.matches()){
            lblErrLast.setText("Invalid last name");
        }else{
        lblErrLast.setText(null);
        person.setLastName(ln);
        }
    }//GEN-LAST:event_txtLastNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooserDob;
    private com.toedter.calendar.JDateChooser jDateChooserLDoi;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBkAccNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDevAdd;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrCity;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrFax;
    private javax.swing.JLabel lblErrFirstName;
    private javax.swing.JLabel lblErrLast;
    private javax.swing.JLabel lblErrPhNo;
    private javax.swing.JLabel lblErrSsn;
    private javax.swing.JLabel lblErrState;
    private javax.swing.JLabel lblErrZip;
    private javax.swing.JLabel lblFaxNo1;
    private javax.swing.JLabel lblFingerIdenNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblIpAdd;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicDoi;
    private javax.swing.JLabel lblLicNo;
    private javax.swing.JLabel lblLinkedInId;
    private javax.swing.JLabel lblLocId;
    private javax.swing.JLabel lblMedRecNo;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblRetinalNo;
    private javax.swing.JLabel lblSelectFile;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTtile;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBkAccNo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDevAdd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFingerIdenNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtIpAdd;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicNo;
    private javax.swing.JTextField txtLinkedInId;
    private javax.swing.JTextField txtLocalIdNo;
    private javax.swing.JTextField txtMedRecNo;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtRetinalNo;
    private javax.swing.JTextField txtSelectFile;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtVehicleNo;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

    
   
    private int findAge(String dob) throws ParseException  {
        //Function to calculate age from date of birth
         int age=0;
         System.out.println("Inside find age");
        
           try{ 
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            Date birthDate=dateFormat.parse(dob);
            Instant instant = birthDate.toInstant();
            ZonedDateTime zone = instant.atZone(ZoneId.systemDefault());
            LocalDate givenDate = zone.toLocalDate();
            Period period = Period.between(givenDate, LocalDate.now());
            age=period.getYears();
            
            } catch (ParseException ex) {
            System.out.println(ex);
            System.out.println("Problem with calculating age");
     
        }
        return age;
    }
  
}
