/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.awt.CardLayout;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clinic;
import model.Patient;

/**
 *
 * @author Milind
 */
public class Community extends javax.swing.JPanel {
    Clinic clinic=Clinic.getInstance();

    /**
     * Creates new form Community
     */
    public Community() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePersonDirectory = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAbnormalName = new javax.swing.JTable();
        jTextSelectCommunity = new javax.swing.JTextField();
        jLabelNumberAbnormal = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCommunityList = new javax.swing.JTable();
        jButtonCommList = new javax.swing.JButton();
        jButtonViewPersonDirectory = new javax.swing.JButton();
        jTextFieldAbormalBloodPressure = new javax.swing.JTextField();
        jLabelSerialNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCheckAbnormal = new javax.swing.JButton();
        jLablesNamesList = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTablePersonDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Mobile", "House"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePersonDirectory);

        jTableAbnormalName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableAbnormalName);

        jLabelNumberAbnormal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumberAbnormal.setText("Number of People with Abnormal Blood Pressure:");

        jTableCommunityList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SerialNo", "ZipCode", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableCommunityList);

        jButtonCommList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCommList.setText("GET COMMUNITY LIST");
        jButtonCommList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommListActionPerformed(evt);
            }
        });

        jButtonViewPersonDirectory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonViewPersonDirectory.setText("VIEW PERSON DIRECTORY");
        jButtonViewPersonDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPersonDirectoryActionPerformed(evt);
            }
        });

        jTextFieldAbormalBloodPressure.setEditable(false);

        jLabelSerialNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSerialNo.setText("Enter Serial Number of Community from Community List:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("PERSON DIRECTORY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("COMMUNITY LIST");

        jButtonCheckAbnormal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCheckAbnormal.setText("CHECK");
        jButtonCheckAbnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckAbnormalActionPerformed(evt);
            }
        });

        jLablesNamesList.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLablesNamesList.setText("LIST OF PEOPLE WITH ABNORMAL BLOOD PRESSURE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COMMUNITY DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButtonViewPersonDirectory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCommList)
                                .addGap(87, 87, 87)))
                        .addComponent(jLabelNumberAbnormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAbormalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelSerialNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonCheckAbnormal)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jTextSelectCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLablesNamesList, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(271, 271, 271))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLablesNamesList, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelSerialNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextSelectCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCheckAbnormal)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewPersonDirectory)
                    .addComponent(jButtonCommList)
                    .addComponent(jLabelNumberAbnormal)
                    .addComponent(jTextFieldAbormalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCommListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommListActionPerformed
        // TODO add your handling code here:
        List<String> getCom=new ArrayList<String>();
        getCom=clinic.listCom();
        DefaultTableModel tbl = (DefaultTableModel) jTableCommunityList.getModel();
        tbl.setRowCount(0);
        int num = getCom.size();
        System.out.println(getCom);
        int y=0;
        for (int i = 0, g=1 , k=2; i < num && g<num &&k<num; i+=3,g+=3,k+=3) {
            Object[] row = new Object[10];
            row[0]=getCom.get(i);
            row[1]=getCom.get(g);
            row[2]=getCom.get(k);
            tbl.addRow(row);

        }
    }//GEN-LAST:event_jButtonCommListActionPerformed

    private void jButtonViewPersonDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPersonDirectoryActionPerformed
        // TODO add your handling code here:
        ArrayList<Patient> patientDirectory=clinic.getList();
        DefaultTableModel tbl = (DefaultTableModel) jTablePersonDirectory.getModel();
        tbl.setRowCount(0);
        //tbl.setRowCount(0);
        int num = patientDirectory.size();
        System.out.println("************************************************************************************\n"
            + "PERSON DIRECTORY                                                                    \n"
            + "************************************************************************************");

        for (int i = 0; i < num; i++) {
            Object[] row = new Object[10];
            row[0]=patientDirectory.get(i).getPersonName();
            row[1]=patientDirectory.get(i).getPersonAge();
            row[2]=patientDirectory.get(i).getMobileNumber();
            row[3]=patientDirectory.get(i).getHouse().getHouseAdress();
            System.out.println(patientDirectory.get(i).toString());
            tbl.addRow(row);
            System.out.println((i + 1) + ". " + patientDirectory.get(i).toString());
        }

        System.out.println("************************************************************************************");

    }//GEN-LAST:event_jButtonViewPersonDirectoryActionPerformed

    private void jButtonCheckAbnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckAbnormalActionPerformed
        // TODO add your handling code here:
        try{
        int getSerial=Integer.parseInt(jTextSelectCommunity.getText());
        List<String> arAb=new ArrayList<String>();
        arAb=clinic.getListABnormal(getSerial);
        System.out.println(arAb);
        DefaultTableModel tbl = (DefaultTableModel) jTableAbnormalName.getModel();
        tbl.setRowCount(0);
        int num = arAb.size();
        for(int i = 0; i < num; i++) {

            Object[] row = new Object[10];
            row[0]=arAb.get(i);
            tbl.addRow(row);
        }

        jTextFieldAbormalBloodPressure.setText(Integer.toString(arAb.size()));
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(null, "Enter valid community Serial No");
         return;
        }
    }//GEN-LAST:event_jButtonCheckAbnormalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckAbnormal;
    private javax.swing.JButton jButtonCommList;
    private javax.swing.JButton jButtonViewPersonDirectory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNumberAbnormal;
    private javax.swing.JLabel jLabelSerialNo;
    private javax.swing.JLabel jLablesNamesList;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableAbnormalName;
    private javax.swing.JTable jTableCommunityList;
    private javax.swing.JTable jTablePersonDirectory;
    private javax.swing.JTextField jTextFieldAbormalBloodPressure;
    private javax.swing.JTextField jTextSelectCommunity;
    // End of variables declaration//GEN-END:variables
}
