/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JPanel;
import javax.swing.plaf.SplitPaneUI;
import model.Clinic;

/**
 *
 * @author Milind
 */
public class MainJFrame extends javax.swing.JFrame {
    Clinic clinic=Clinic.getInstance();
    CardLayout cardLayout;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        try {
            getInitialContents();
        } catch (IOException ex) {
            System.out.println("Error in Initialization");
        }
        cardLayout=(CardLayout)(jPanel2.getLayout());
    }

    
    public void getInitialContents() throws FileNotFoundException, IOException
    
    {
        
        Scanner s = new Scanner(new File("newfile.txt"));
        s.useDelimiter(",");
ArrayList<String> list = new ArrayList<String>();
while (s.hasNext()){
    list.add(s.next());
}
s.close();

        for(int i=0;i<(list.size()-10);i+=10)
        {
            System.out.println(i);
            int res=Integer.parseInt(list.get(i+6));
            
            System.out.println(res);
            int age=Integer.parseInt(list.get(i+1));
            int heart=Integer.parseInt(list.get(i+7));
                     int bp=Integer.parseInt(list.get(i+8));
                         int kg=Integer.parseInt(list.get(i+9));
            clinic.addnewPatienttoTheDirectory(list.get(i),age,list.get(i+2),list.get(i+3),list.get(i+4),list.get(i+5),res,heart,bp,kg);
        
        
        



    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddPatient = new javax.swing.JButton();
        ManageEncounterVisitToPresent = new javax.swing.JButton();
        jButtonGetCommunityStats = new javax.swing.JButton();
        jButtonUpdateDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonAddPatient.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButtonAddPatient.setText("REGISTER PATIENT");
        jButtonAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatientActionPerformed(evt);
            }
        });

        ManageEncounterVisitToPresent.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        ManageEncounterVisitToPresent.setText("MANAGE PATIENT");
        ManageEncounterVisitToPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEncounterVisitToPresentActionPerformed(evt);
            }
        });

        jButtonGetCommunityStats.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButtonGetCommunityStats.setText("COMMUNITY DETAILS");
        jButtonGetCommunityStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetCommunityStatsActionPerformed(evt);
            }
        });

        jButtonUpdateDetails.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButtonUpdateDetails.setText("UPDATE DETAILS");
        jButtonUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDetailsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PATIENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(ManageEncounterVisitToPresent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUpdateDetails))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddPatient)
                                .addGap(494, 494, 494)
                                .addComponent(jButtonGetCommunityStats)))
                        .addGap(60, 60, 60)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddPatient)
                            .addComponent(jButtonGetCommunityStats))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageEncounterVisitToPresent)
                    .addComponent(jButtonUpdateDetails))
                .addContainerGap())
        );

        jSplitPane2.setTopComponent(jPanel1);

        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatientActionPerformed
        // TODO add your handling code here:
        AddPatientPanel panel = new AddPatientPanel();
        jPanel2.add("AddPatientPanel",panel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_jButtonAddPatientActionPerformed

    private void ManageEncounterVisitToPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEncounterVisitToPresentActionPerformed
         ManageExistingPatient panel = new ManageExistingPatient();
        jPanel2.add("ManageExistingPatient",panel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);       
// TODO add your handling code here:
        
    }//GEN-LAST:event_ManageEncounterVisitToPresentActionPerformed

    private void jButtonGetCommunityStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetCommunityStatsActionPerformed
        // TODO add your handling code here:
        Community panel = new  Community();
        jPanel2.add("Community",panel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_jButtonGetCommunityStatsActionPerformed

    private void jButtonUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDetailsActionPerformed
        // TODO add your handling code here:
        
         UpdateDetailsPerson panel = new UpdateDetailsPerson();
        jPanel2.add("UpdateDetailsPerson",panel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_jButtonUpdateDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEncounterVisitToPresent;
    private javax.swing.JButton jButtonAddPatient;
    private javax.swing.JButton jButtonGetCommunityStats;
    private javax.swing.JButton jButtonUpdateDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
