/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Clinic;
import model.Patient;

/**
 *
 * @author Milind
 */
public class UpdateDetailsPerson extends javax.swing.JPanel {
    Clinic clinic=Clinic.getInstance();

    /**
     * Creates new form UpdateDetailsPerson
     */
    public UpdateDetailsPerson() {
        initComponents();
        jButtonUpdate.setEnabled(false);    
        jTextFieldName.setEnabled(false);
        jTextFieldHouse1.setEnabled(false);
        jTextFieldNewMobileNumber.setEnabled(false);
        jTextFieldNewMobile.setEnabled(false);
        
        
    }
    
    private int checkIfNumberALreadyExists(String mobileNumber) {
        ArrayList<Patient> patientDirectory=clinic.getList();
        for (int i = 0; i < patientDirectory.size(); i++) {

            {
                if (patientDirectory.get(i).getMobileNumber() == null ? mobileNumber == null : patientDirectory.get(i).getMobileNumber().equals(mobileNumber)) {
                    System.out.println("Enterd number is linked to " + patientDirectory.get(i).getPersonName());
                   
                    return i;
                    
                    
                }
            }

        }
        return -1;
    }
    
    public void updateDetails(){
        
     String mobile=jTextFieldMobileNumber.getText();
    String house=jTextFieldHouse1.getText();
    ArrayList<Patient> patientDirectory=clinic.getList();
    int index=checkIfNumberALreadyExists(mobile);
    patientDirectory.get(index).getHouse().setHouseAdress(house);
    
   
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMobile = new javax.swing.JLabel();
        jTextFieldMobileNumber = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelHouse = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldHouse1 = new javax.swing.JTextField();
        jButtonCheck = new javax.swing.JButton();
        jLabelNewMobile = new javax.swing.JLabel();
        jTextFieldNewMobile = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabelNewMobileNumber = new javax.swing.JLabel();
        jTextFieldNewMobileNumber = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE DETAILS");

        jLabelMobile.setText(" Mobile Number:");

        jTextFieldMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMobileNumberActionPerformed(evt);
            }
        });

        jLabelName.setText("Name:");

        jLabelHouse.setText(" House:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldHouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHouse1ActionPerformed(evt);
            }
        });

        jButtonCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCheck.setText("VALIDATE");
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });

        jLabelNewMobile.setText(" Current Mobile Number:");

        jTextFieldNewMobile.setEditable(false);
        jTextFieldNewMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewMobileActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUpdate.setText("SAVE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabelNewMobileNumber.setText(" New Mobile Number:");

        jTextFieldNewMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewMobileNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMobile)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelNewMobile)
                                    .addComponent(jLabelHouse)
                                    .addComponent(jLabelNewMobileNumber))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCheck))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNewMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNewMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 259, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButtonUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMobile)
                    .addComponent(jButtonCheck))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHouse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHouse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewMobile)
                    .addComponent(jTextFieldNewMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewMobileNumber)
                    .addComponent(jTextFieldNewMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobileNumberActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldHouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHouse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHouse1ActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
        // TODO add your handling code here:
        String mobile=jTextFieldMobileNumber.getText();
        int inde=checkIfNumberALreadyExists(mobile);
        System.out.println("found" +inde);
        if (checkIfNumberALreadyExists(mobile) != -1) { 
                     
                     jTextFieldName.setEnabled(true);
                    jTextFieldHouse1.setEnabled(true);
                    jTextFieldNewMobileNumber.setEnabled(true);
                    jTextFieldNewMobile.setEnabled(true);
                    jButtonUpdate.setEnabled(true);
                    int index=checkIfNumberALreadyExists(mobile);
                    ArrayList<Patient> patientDirectory=clinic.getList();
                    jTextFieldHouse1.setText(patientDirectory.get(index).getHouse().getHouseAdress());
                    jTextFieldName.setText(patientDirectory.get(index).getPersonName());
                    
                    
                    jTextFieldNewMobile.setText(patientDirectory.get(index).getMobileNumber());
                    JOptionPane.showMessageDialog(null, "Patient exist!");
                    
                    
                    
                    
                }
        else{
        JOptionPane.showMessageDialog(null, "No data found!");}
    }//GEN-LAST:event_jButtonCheckActionPerformed

    private void jTextFieldNewMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewMobileActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
    
    String mobile=jTextFieldMobileNumber.getText();
    
    ArrayList<Patient> patientDirectory=clinic.getList();
    int index=checkIfNumberALreadyExists(mobile);
    String house=jTextFieldHouse1.getText();
   
    String name=jTextFieldName.getText();
    
    
    if(!"".equals(jTextFieldNewMobileNumber.getText())){
    try
        {
        String phNo=jTextFieldNewMobileNumber.getText();
        String PATTERN="^[0-9]{3}[0-9]{3}[0-9]{4}$";
       
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(phNo);
        if (!match.matches()){
            throw new Exception();
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid 10 digit Mobile number!");
            return;
            
        }}
    
    
        if(!"".equals(jTextFieldNewMobileNumber.getText())){
            for(int i=0;i<patientDirectory.size();i++){
        try{
        
        if(patientDirectory.get(i).getMobileNumber().equals(jTextFieldNewMobileNumber.getText())){
        
             throw new Exception();
            
            
        }
       
        }
        
        catch(Exception e){
            
          JOptionPane.showMessageDialog(null, "Mobile number already exists!");
          return;
        
        }}}
        else{
             patientDirectory.get(index).setMobileNumber(jTextFieldNewMobile.getText());
        }
        
    
    if(!"".equals(jTextFieldNewMobileNumber.getText())){
    patientDirectory.get(index).setMobileNumber(jTextFieldNewMobileNumber.getText());
    }
    patientDirectory.get(index).getHouse().setHouseAdress(house);
    patientDirectory.get(index).setPersonName(name);
    JOptionPane.showMessageDialog(null, "Update successful");
    jTextFieldMobileNumber.setText(null);
     jTextFieldName.setText(null);
     jTextFieldHouse1.setText(null);
      jTextFieldNewMobile.setText(null);
      jTextFieldNewMobileNumber.setText(null);
     
     
    
    
    
    
    
    
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldNewMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewMobileNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHouse;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNewMobile;
    private javax.swing.JLabel jLabelNewMobileNumber;
    private javax.swing.JTextField jTextFieldHouse1;
    private javax.swing.JTextField jTextFieldMobileNumber;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNewMobile;
    private javax.swing.JTextField jTextFieldNewMobileNumber;
    // End of variables declaration//GEN-END:variables
}
